# Generated by Django 4.2.20 on 2025-03-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('sum', 'Soma'), ('average', 'Média')], max_length=20)),
                ('input_numbers', models.CharField(help_text='Números usados na operação (armazenados como string)', max_length=255)),
                ('result', models.FloatField(help_text='Resultado da operação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
